### ISSUE TITLE
Support vhost

### ISSUE THREAD

**Issue by truongsinh** [gocraft/web#44]
Instead of of workaround using built-in http://golang.org/pkg/net/http/#ServeMux (http://stackoverflow.com/questions/14170799/how-to-get-virtualhost-functionality-in-go) , can we do it directly in go craft web?

**Comment by cypriss** [comment]
To be clear, the workaround is pretty viable: create multiple routers, and pass them into the Handle function with different hosts: http://golang.org/pkg/net/http/#ServeMux.Handle

The feature being requested here is to add the host as a route-able parameter. Not ruling it out, but it seems a little bloaty to be in gocraft/web.

**Comment by cypriss** [comment]
Closing.
