### ISSUE TITLE
appendPath func inconsistency

### ISSUE THREAD

**Issue by wanton7** [gocraft/web#50]
Works

	router := web.New(Context{})
	router = router.Subrouter(Context{}, "/")
	router.Get("/", index)

Panics

	router := web.NewWithPrefix(Context{}, "/test")
	router = router.Subrouter(Context{}, "/")
	router.Get("/", index)

Works

	router := web.NewWithPrefix(Context{}, "/test")
	router = router.Subrouter(Context{}, "")
	router.Get("", index)

**Comment by wanton7** [comment]
I would have done a pull request but i don't really know git that well.

This should fix the problem

func appendPath(rootPath, childPath string) string {
	return strings.TrimRight(rootPath, "/") + "/" + strings.TrimLeft(childPath, "/")
}

**Comment by cypriss** [comment]
@wanton7 fixed. thx
